### ISSUE TITLE
Add prettier linter for web and markdown files

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Hacktoberfest#9]
### Background on the problem the feature will solve/improved user experience
Add `prettier` linter for all files in this repo except node_modules folder. Okay to use the default config for now.

### Describe the solution you'd like
Add GitHub action that checks for linting issues on every branch push and PR created. You can use the following to start with:

```
name: lint

on:
  push:
    branches:
      - "**"
  pull_request_target:
    branches:
      - main
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
      - run: npm install -g prettier@2.3.0
      - run: prettier --check .
```

### Tasks 
- [ ] add lint.yml to .github/workflows/
- [ ] ensure github action is working by looking at the logs on commit

### Acceptance Criteria 
GitHub action runs no every push and PR created to lint the web and markdown files. The PR is not merged if the linter reports issues with the files.

FYI @demilolu
